# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/rpc/review_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/rpc/review_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1csrc/rpc/review_service.proto\x12\x06review\"b\n\x0e\x45xecuteRequest\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x11\n\tdata_json\x18\x02 \x01(\t\x12\x11\n\targs_json\x18\x03 \x01(\t\x12\x13\n\x0bkwargs_json\x18\x04 \x01(\t\"N\n\x0f\x45xecuteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bresult_json\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t2U\n\x15ReviewFunctionService\x12<\n\x07\x45xecute\x12\x16.review.ExecuteRequest\x1a\x17.review.ExecuteResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.rpc.review_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTEREQUEST']._serialized_start=40
  _globals['_EXECUTEREQUEST']._serialized_end=138
  _globals['_EXECUTERESPONSE']._serialized_start=140
  _globals['_EXECUTERESPONSE']._serialized_end=218
  _globals['_REVIEWFUNCTIONSERVICE']._serialized_start=220
  _globals['_REVIEWFUNCTIONSERVICE']._serialized_end=305
# @@protoc_insertion_point(module_scope)
